PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,phone TEXT NOT NULL UNIQUE,name_ar TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('owner','operator','admin','auditor')),active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS units(id TEXT PRIMARY KEY,building_no INTEGER NOT NULL,unit_no INTEGER NOT NULL,owner_id TEXT REFERENCES users(id),annual_due_piastres INTEGER NOT NULL DEFAULT 0 CHECK(typeof(annual_due_piastres)='integer' AND annual_due_piastres>=0),UNIQUE(building_no,unit_no));
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS login_codes(phone TEXT PRIMARY KEY,code_hash TEXT NOT NULL,expires_at TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payment_categories(id TEXT PRIMARY KEY,name_ar TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN('income','deposit')));
CREATE TABLE IF NOT EXISTS payments(id TEXT PRIMARY KEY,unit_id TEXT NOT NULL REFERENCES units(id),category_id TEXT NOT NULL REFERENCES payment_categories(id),amount_piastres INTEGER NOT NULL CHECK(typeof(amount_piastres)='integer' AND amount_piastres>0),method TEXT NOT NULL,transfer_date TEXT NOT NULL,reference_no TEXT,note_ar TEXT,receipt_data TEXT,status TEXT NOT NULL CHECK(status IN('submitted','in_review','approved','rejected','needs_info','cancelled')),submitted_by TEXT NOT NULL REFERENCES users(id),reviewed_by TEXT REFERENCES users(id),review_reason TEXT,created_at TEXT NOT NULL,reviewed_at TEXT);
CREATE TABLE IF NOT EXISTS expenses(id TEXT PRIMARY KEY,title_ar TEXT NOT NULL,category_ar TEXT NOT NULL,amount_piastres INTEGER NOT NULL CHECK(typeof(amount_piastres)='integer' AND amount_piastres>0),expense_date TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),approved_by TEXT REFERENCES users(id),status TEXT NOT NULL CHECK(status IN('draft','pending','approved','rejected')),invoice_data TEXT,note_ar TEXT,created_at TEXT NOT NULL,approved_at TEXT);
CREATE TABLE IF NOT EXISTS announcements(id TEXT PRIMARY KEY,title_ar TEXT NOT NULL,body_ar TEXT NOT NULL,pinned INTEGER NOT NULL DEFAULT 0,published INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,actor_id TEXT,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,details_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ledger_entries(id TEXT PRIMARY KEY,source_type TEXT NOT NULL,source_id TEXT NOT NULL UNIQUE,account TEXT NOT NULL,amount_piastres INTEGER NOT NULL CHECK(typeof(amount_piastres)='integer' AND amount_piastres<>0),fund TEXT NOT NULL CHECK(fund IN('operating','deposit')),created_at TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS no_ledger_update BEFORE UPDATE ON ledger_entries BEGIN SELECT RAISE(ABORT,'السجل المالي لا يتعدل'); END;
CREATE TRIGGER IF NOT EXISTS no_ledger_delete BEFORE DELETE ON ledger_entries BEGIN SELECT RAISE(ABORT,'السجل المالي لا يتمسح'); END;
CREATE TRIGGER IF NOT EXISTS no_audit_update BEFORE UPDATE ON audit_log BEGIN SELECT RAISE(ABORT,'سجل المراجعة لا يتعدل'); END;
CREATE TRIGGER IF NOT EXISTS no_audit_delete BEFORE DELETE ON audit_log BEGIN SELECT RAISE(ABORT,'سجل المراجعة لا يتمسح'); END;
CREATE INDEX IF NOT EXISTS idx_payments_unit ON payments(unit_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status,created_at);
CREATE INDEX IF NOT EXISTS idx_expenses_status ON expenses(status,created_at);
INSERT OR IGNORE INTO users VALUES('USR-ADMIN','01000000004','مدير النظام التجريبي','admin',1,datetime('now'));
INSERT OR IGNORE INTO users VALUES('USR-OWNER','01000000001','د. أحمد محمود','owner',1,datetime('now'));
INSERT OR IGNORE INTO users VALUES('USR-OP','01000000002','مشغل القرية','operator',1,datetime('now'));
INSERT OR IGNORE INTO units VALUES('UNIT-5-12',5,12,'USR-OWNER',150000);
INSERT OR IGNORE INTO payment_categories VALUES('maintenance','اشتراك الصيانة','income');
INSERT OR IGNORE INTO payment_categories VALUES('deposit','الوديعة','deposit');
INSERT OR IGNORE INTO announcements VALUES('ANN-1','اجتماع الجمعية العمومية','الجمعة 14 أغسطس الساعة 8 مساءً في مقر الإدارة.',1,1,'USR-ADMIN',datetime('now'));
